# Generated by Django 2.2.3 on 2019-07-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='harga',
            field=models.CharField(max_length=100),
        ),
    ]
